FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml .
COPY uv.lock .
RUN uv sync --no-dev
COPY app/ app/
COPY data/ data/
EXPOSE 8001
CMD ["uv","run","uvicorn","app.main:app","--host","0.0.0.0","--port","8001"]
