import type { CalendarSchedule } from "./types";

export const mockSchedules: CalendarSchedule[] = [
  {
    id: "schedule-1",
    title: "기말 발표 준비",
    detail: "딥러닝 논문 리뷰 발표 자료를 정리하고 발표 흐름을 만든다.",
    location: "공학관 B204",
    start_time: "2026-06-07T09:30:00",
    end_time: "2026-06-07T11:30:00",
    status: "ok",
    tasks: [
      {
        id: "task-1",
        title: "논문 핵심 주장 정리",
        description: "서론, 방법, 실험, 한계를 한 페이지로 압축한다.",
        estimated_minutes: 35,
        order_index: 1,
        is_done: false,
      },
      {
        id: "task-2",
        title: "슬라이드 구조 작성",
        description: "10장 기준으로 제목과 핵심 메시지를 배치한다.",
        estimated_minutes: 45,
        order_index: 2,
        is_done: false,
      },
      {
        id: "task-3",
        title: "발표 리허설",
        description: "12분 안에 끝나는지 확인한다.",
        estimated_minutes: 30,
        order_index: 3,
        is_done: true,
      },
    ],
  },
  {
    id: "schedule-2",
    title: "프로젝트 회고",
    detail: "팀 작업 흐름과 다음 스프린트 리스크를 점검한다.",
    location: "온라인",
    start_time: "2026-06-07T14:00:00",
    end_time: "2026-06-07T15:00:00",
    status: "needs_question",
    tasks: [],
  },
  {
    id: "schedule-3",
    title: "API 계약 점검",
    detail: "프론트 요청 body와 FastAPI 스키마를 맞춘다.",
    location: "개발실",
    start_time: "2026-06-08T10:00:00",
    end_time: "2026-06-08T12:00:00",
    status: "pending",
    tasks: [
      {
        id: "task-4",
        title: "일정 수정 payload 확인",
        description: "시간 필드가 전송되지 않는지 확인한다.",
        estimated_minutes: 20,
        order_index: 1,
        is_done: false,
      },
      {
        id: "task-5",
        title: "SSE done 이벤트 샘플 정리",
        description: "재생성 흐름에 필요한 필드를 기록한다.",
        estimated_minutes: 25,
        order_index: 2,
        is_done: false,
      },
    ],
  },
  {
    id: "schedule-4",
    title: "배포 리허설",
    detail: "Railway API와 Vercel 환경변수 구성을 확인한다.",
    location: "회의실 A",
    start_time: "2026-06-09T16:00:00",
    end_time: "2026-06-09T17:30:00",
    status: "fallback",
    tasks: [],
  },
];
